name: Makefile CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: dmcoles/amiga-evo-cicd
      credentials:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
    steps: 
      - uses: actions/checkout@v4
      - name: run build
        run: |
           vamos -c /usr/amiga/.vamosrc --cwd esource: -V system:/usr/amiga -V esource:$GITHUB_WORKSPACE make build=release

      - name: add build artifacts to publish
        run: |
          apk add lha
          mkdir downloads
          cp $GITHUB_WORKSPACE/rebuild downloads
          cp $GITHUB_WORKSPACE/Rebuild.info downloads
          cp $GITHUB_WORKSPACE/Rebuild_manual.txt downloads
          cp $GITHUB_WORKSPACE/Rebuild_manual.txt.info downloads
          cd downloads
          lha a ../rebuild-nightly${{ github.sha }}.lha *
          ls ../
         
      - name: Update nightly release
        uses: pyTooling/Actions/releaser@main
        with:
          tag: dev-build
          rm: true
          token: ${{ secrets.GITHUB_TOKEN }}
          files: rebuild-nightly${{ github.sha }}.lha
